on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-daily-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

            - name: Run script
        run: bash daily-log.sh
      
enable push trigger
