name: Daily Automation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-daily-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fix line endings
        run: sed -i 's/\r$//' daily-log.sh

      - name: Run script
        run: bash daily-log.sh

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add DAILY_LOG.md
          git commit -m "Auto update log" || echo "No changes"
          git push
