name: Daily Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  run-daily-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run daily script
        run: |
          chmod +x daily-log.sh
          ./daily-log.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "auto daily update" || echo "No changes"
          git push
