name: Daily Automation

on:
  workflow_dispatch:

jobs:
  run-daily-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: |
          chmod +x daily-log.sh
          ./daily-log.sh
